package com.voligov.movieland.util;

public class Constant {
    public static final String ORDER_BY = "ORDER BY";
    public static final String RATING = "rating";
    public static final String PRICE = "price";
    public static final String LIMIT = "LIMIT";
    public static final String WHERE = "WHERE";
    public static final String LIKE = "LIKE";
    public static final String AND = "AND";
    public static final String COMMA = ",";
    public static final String SPACE = " ";
    public static final String SEMICOLON = ";";
    public static final String QUOTE = "'";
    public static final String PERCENT = "%";
    public static final String BRACKET_OPEN = "[";
    public static final String BRACKET_CLOSE = "]";
    public static final String GENRES = "genres";
    public static final String COUNTRIES = "countries";
    public static final String NAME = "name";
    public static final String NAME_ORIGINAL = "name_original";
    public static final String RELEASE_YEAR = "release_year";
    public static final String DESCRIPTION = "description";
    public static final String ADDED_TIMESTAMP = "added_ts";
    public static final String UPDATED_TIMESTAMP = "updated_ts";
    public static final String REVIEW_COUNT = "review_count";
    public static final String TEXT = "text";
    public static final String FIRST_NAME = "first_name";
    public static final String LAST_NAME = "last_name";
    public static final String EMAIL = "email";
    public static final String PASSWORD = "password";
    public static final String ROLE = "role";
    public static final String REQUEST_ID = "requestId";
    public static final String TOKEN = "token";
    public static final String AUTHORIZED_USER = "authorizedUser";
    public static final String USER = "user";
    public static final String GUEST = "guest";
    public static final String MOVIE_IDS = "movieIds";
    public static final String ERROR = "error";
    public static final String ID = "id";
    public static final String MOVIE_ID = "movie_id";
    public static final String USER_ID = "user_id";
    public static final String V1_PATH = "/v1/";
    public static final String SENDGRID_API_KEY = "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";
    public static final String SENDGRID_URI = "https://api.sendgrid.com/v3/mail/send";
    public static final String ERROR_EMAIL_SENDER = "movieland@mail.com";
    public static final String ERROR_EMAIL_RECIEVER = "sands47@gmail.com";
    public static final String PRIVAT_NBU_API_URI = "https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=3";
}
